baseurl = "http://iplus-hackathon.futurehack.fi/"
languageCode = "en-us"
title = "I+ Hackathon"
theme = "iplus-theme"

[params]

  # You can use Markdown for urls [text](//domain.tld/source)
  #
  # All icons using Fontawesom's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
  # for more icons.

  # To provide more meta data for search engings feel free to add a few informations.
  # This lines will be inserted as meta tags.
  name = "Ihminen+ Hackathon"
  description = "Lorem Ipsum Dolor Sit Amet"

  # For a static site it's not possible to provide a contact form. The contact form uses
  # www.formspree.io as a proxy. The form makes a Post request to their servers to send an email
  # Visitors can send up to a 1000 emails each month
  #
  # How to setup formspree
  #
  # - set your email address under 'email' below
  # - upload the generated site to your server
  # - send a dummy email to yourself to confirm your account
  # - click the confirmation link in the email from www.formspree.io
  # - That's all. Enjoy mailing!
  email = "ilmo.euro@gmail.com"

  # Hero Section
  [params.hero]
    title = "I+ Hackathon"
    description = "Lorem ipsum"
    buttonText = "Dolor sit amet"

  # about section
  [params.about]
    enable = true
    title = "About"
    description = "Aliquam ante ac id. Adipiscing interdum lorem praesent fusce pellentesque arcu feugiat. Consequat sed ultricies rutrum. Sed adipiscing eu amet interdum lorem blandit vis ac commodo aliquet integer vulputate phasellus lorem ipsum dolor lorem magna consequat sed etiam adipiscing interdum."
    buttonText = "next"
    # the picture is storead at static/images/
    # picture = "bg.jpg"

  # skill section
  [params.skill_list]
    enable = false

  [params.infos]
    enable = true
    title = "Challenges"
    description = "Aliquam ante ac id. Adipiscing interdum lorem praesent fusce pellentesque arcu feugiat. Consequat sed ultricies rutrum. Sed adipiscing eu amet interdum lorem blandit vis ac commodo aliquet integer vulputate phasellus lorem ipsum dolor lorem magna consequat sed etiam adipiscing interdum."
    # the picture is storead at static/images/
    # picture = "bg.jpg"

  # footer section
  # this section includes
  #
  # - the contact form
  # - social icons
  #
  # It's possible to disable the whole footer or disable only social icons or contact form

  [params.footer]
    enable = true
    title = "Get in Touch"

    # contact form
    [params.footer.contact]
      enable = true

    [params.footer.contact.form]
      name = "Name"
      email = "Your Email"
      message = "Your Message"
      buttonText = "send message"

    # social icons
    [params.footer.social_list]
      enable = true

      [[params.footer.social]]
        title = "Twitter"
        icon = "fa-twitter"
        link = "#"

      [[params.footer.social]]
        title = "Facebook"
        icon = "fa-facebook"
        link = "#"

      [[params.footer.social]]
        title = "Instagramm"
        icon = "fa-instagram"
        link = "#"

      [[params.footer.social]]
        title = "Email"
        icon = "fa-envelope"
        link = "#"

    # copyright
    #[params.footer.copyright.notice]

      [[params.footer.copyright.notice]]
        text = "© Otavan Opisto 2016"

      [[params.footer.copyright.notice]]
        text = "Design: Ilmo Euro & [HTML5UP](//html5up.net)"

      [[params.footer.copyright.notice]]
        text = "Demo Images: [Unsplash](//unsplash.com/)"
