baseurl = "http://hack.ihminenplus.fi/"
languageCode = "en-us"
title = "I+ Hackathon"
theme = "iplus-theme"
destionation = "docs"

[params]

  # You can use Markdown for urls [text](//domain.tld/source)
  #
  # All icons using Fontawesom's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
  # for more icons.

  # To provide more meta data for search engings feel free to add a few informations.
  # This lines will be inserted as meta tags.
  name = "Ihminen+ Hack"
  description = "Hackathon for Ihminen+ Event"

  # For a static site it's not possible to provide a contact form. The contact form uses
  # www.formspree.io as a proxy. The form makes a Post request to their servers to send an email
  # Visitors can send up to a 1000 emails each month
  #
  # How to setup formspree
  #
  # - set your email address under 'email' below
  # - upload the generated site to your server
  # - send a dummy email to yourself to confirm your account
  # - click the confirmation link in the email from www.formspree.io
  # - That's all. Enjoy mailing!
  email = "ilmo.euro@gmail.com"

  # Hero Section
  [params.hero]
    title = "Ihminen+ Hack"
    description = """
A hackathon about human future and technology <br/>
Mikkeli 17.&mdash;18.9.2016
"""
    buttonText = "More information"

  # about section
  [params.about]
    enable = true
    title = "About"
    description = """
Ihminen+ Hack is a hackathon accompanying the [Ihminen+
seminar](http://www.ihminenplus.fi/). The events are independent, so you can
sign up to the hackathon without attending the seminar.  Prizes will be given
out in 3 categories: Human Upgrade, Future Vision and People's Choice. The
winning team of each category will receive awesome prizes and tickets to
the main seminar event. Teams are limited to 4 members.

<p style="text-align: center;margin-top:3.5em;margin-bottom:5.5em;">
    <a class="button special"
       style="background-color: #fa0;padding-left: 1.5em;padding-right:1.5em;"
       href="https://goo.gl/forms/hcjI7A97KJ7qv9wx1">Sign up now!</a>
    
</p>

#### What is a hackathon?

Hackathon is an event where people get together to solve problems, explore new
technology, make awesome things, have fun, learn from each other and perhaps
develop something useful while doing so. Hackathons are built around technology.

Sure, taking part in a hackathon exposes you to technology and coding. But not
everyone needs to be a programmer. Hackathon needs all kinds of skills from
graphics design and storytelling to health and medical expertise and
out-of-the-box thinking. If you enjoy challenging yourself and social learning,
a hackathon is an event for you.

The objective in each hackathon is to build a demo or a prototype - often
software. It can be done for fun, for the challenge or for the prize. It can be
something useful or entertaining or perhaps done simply because you could do so.

To this end, prepare to hang around with people with different backgrounds and
skills. The best teams are those with programmers, designers, subject experts
and even a mad scientist. And definitely, the best team is with you.

#### Location

Xinno, MAMK main campus <br/>
Prikaatinkatu 3 <br/>
50100 Mikkeli <br/>

#### Date

17.&mdash;18.9.2016

#### Schedule

<table>
<tr><td>      </td><th> Saturday 17.9.2016</th></tr>
<tr><td>10:00 </td><td> Registration and coffee</td></tr>
<tr><td>11:00 </td><td> Event opening</td></tr>
<tr><td>      </td><td> Track and challenges introductions</td></tr>
<tr><td>      </td><td> Team matchmaking</td></tr>
<tr><td>12:00 </td><td> Hacking</td></tr>
<tr><td>14:00 </td><td> Buffet lunch</td></tr>
<tr><td>17:30 </td><td> Food available</td></tr>
<tr><td>18:00 </td><td> Sauna for women</td></tr>
<tr><td>19:30 </td><td> Sauna for men</td></tr>
<tr><td>22:00 </td><td> Survival packs for the night</td></tr>
<tr><td>      </td><th> Sunday 18.9.2016</th></tr>
<tr><td>9:00  </td><td> Breakfast available</td></tr>
<tr><td>12:00 </td><td> Presentations & Demos</td></tr>
<tr><td>14:00 </td><td> Food</td></tr>
<tr><td>14:30 </td><td> Robot War side event</td></tr>
<tr><td>16:00 </td><td> Awards ceremony</td></tr>
<tr><td>17:00 </td><td> Closing</td></tr>
</table>

<p style="text-align: center;margin-top:1.5em;margin-bottom:1.5em;">
    More information about tracks below.
</p>

"""
    buttonText = "next"
    # the picture is storead at static/images/
    # picture = "bg.jpg"

  # skill section
  [params.skill_list]
    enable = true
    title = "Human Upgrade"
    description = """

Human Upgrade is a technical track for hacking functional prototypes - mock-ups
and presentations are not enough.  Your prototype is judged based on what works,
not how the prototype is supposed to work.

## Challenges

### Human-Computer Interaction

Find new ways for humans to interact with computers. This could mean a new kind
of user interface, possibly gesture- or movement-based, new ways to visualize
information or a new form of interface between a human and a computer.

#### Example projects

 * Instrument played with your gestures
 * Visualization for exploring open data trends
 * Head tracker used for controlling mouse cursor

#### Materials available for projects

 * Myo gesture sensor (http://www.myo.com)
 * Leap Motion gesture sensor (http://www.leapmotion.com)
 * Arduino-based motion, direction and touch sensor modules

### Cognitive Computing

Give your computer a brain! This challenge is about expanding computing to areas
that are traditionally more suitable for humans. Some of the many applicable
technologies are machine learning, fuzzy logic, computer vision, natural
language processing and evolutionary computation.

#### Example projects

 * Virtual digital assistant for lawyers
 * Computer vision system for determining the alertness level of a person
 * Program for summarizing long articles

### Virtual reality and Augmented reality

Merge the computer's world with your own in this challenge. Either make
creations that immerse others totally in their man-made world, or combine the
best parts of virtual and physical reality.

#### Example projects

 * Augmented reality game
 * 3D virtual reality web browser 
 * Virtual environment for exploring the mechanics of a car engine

### Wearable electronics

Augment yourself with self-made digital gadgets. We provide the materials for
building devices that can measure your body and movement, and interface with
smart phones or computers.

#### Example projects

 * T-shirt with flashing lights
 * Posture sensor/alarm
 * Sports tracker

#### Materials available for projects

 * Lilypad sewable electronic modules
 * T-shirts

### Open challenge

Build anything! We accept functional prototypes that don't fit in the other
categories.

## Prizes

Each member of the winning team gets a *Nintendo 2DS* handheld game console.

"""

  [params.infos]
    enable = true
    title = "Future visions"
    description = """
Future Visions is a track for presenting and visualizing your vision of the
future. The result can be a presentation, a video, a 3D model, a miniature
model, or some other way to communicate your idea to others. Product ideas,
utopias, simulations, and concepts are all welcome. Use your imagination!
Your concept is judged based on its freshness, vision, imaginativeness and
presentation.

## Challenges

### Society and everyday life

Now it's your time to make a difference. Either propose a small improvement to
the ways things are done around you, or present wild visions of a world order
that would be right in your opinion. 

### Smart city

What would the city of the future look like? How do new technologies and the
recent explosion of available data shape metropolises? Present your ideal city,
or just your outlook on the direction cities are moving towards.

### Transportation

How do people travel in the future &mdash; or do they travel at all?
Transportation is an important part of cultural and economic development.
Show us how you think the technology of moving around advances in the future.

### Learning

Learning is more than just sitting in a classroom. How does education and
everyday learning change in the future? Are universities, schools and classrooms
on their way out, or do they grow stronger? Present your vision!

### Open challenge

Present anything! We also accept presentations that don't fit in the other
categories.

## Prizes

Each member of the winning team gets a *Polar Loop 2* activity tracker.

<p>
    <img src="/images/oo_logo.svg" alt="Otavan Opisto">
    <img src="/images/mamk_logo.svg" alt="MAMK">
    <img src="/images/vipuvoimaa_logo.svg" alt="Vipuvoimaa EU:lta 2014-2020">
</p>
"""
    # the picture is storead at static/images/
    # picture = "bg.jpg"

  # footer section
  # this section includes
  #
  # - the contact form
  # - social icons
  #
  # It's possible to disable the whole footer or disable only social icons or contact form

  [params.footer]
    enable = false
    title = "Get in Touch"

    # contact form
    [params.footer.contact]
      enable = true

    [params.footer.contact.form]
      name = "Name"
      email = "Your Email"
      message = "Your Message"
      buttonText = "send message"

    # social icons
    [params.footer.social_list]
      enable = true

      [[params.footer.social]]
        title = "Twitter"
        icon = "fa-twitter"
        link = "#"

      [[params.footer.social]]
        title = "Facebook"
        icon = "fa-facebook"
        link = "#"

      [[params.footer.social]]
        title = "Instagramm"
        icon = "fa-instagram"
        link = "#"

      [[params.footer.social]]
        title = "Email"
        icon = "fa-envelope"
        link = "#"

    # copyright
    #[params.footer.copyright.notice]

      [[params.footer.copyright.notice]]
        text = "© Otavan Opisto 2016"

      [[params.footer.copyright.notice]]
        text = "Design: Ilmo Euro & [HTML5UP](//html5up.net)"

      [[params.footer.copyright.notice]]
        text = "Demo Images: [Unsplash](//unsplash.com/)"
